# Generated by Django 4.2.5 on 2023-09-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_alternative_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='LinkedIn Profile'),
        ),
    ]
