# Generated by Django 4.2.5 on 2023-09-27 12:42

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_corporate_member',
            field=models.BooleanField(default=False, verbose_name='Is Corporate Member'),
        ),
        migrations.AlterField(
            model_name='user',
            name='leadership_role',
            field=models.CharField(blank=True, choices=[('Patron', 'Patron'), ('President', 'President'), ('Deputy President', 'Deputy President'), ('Project Coordinator', 'Project Coordinator'), ('Secretary General', 'Secretary General'), ('Treasurer', 'Treasurer'), ('Organizing Secretary', 'Organizing Secretary'), ('Publicity Secretary', 'Publicity Secretary'), ('Deputy Publicity Secretary', 'Deputy Publicity Secretary'), ('Welfare secretary', 'Welfare Secretary')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=authentication.models.profile_image_file_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='registration_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
