# Generated by Django 4.2.6 on 2023-11-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
        ('authentication', '0010_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blogs',
            field=models.ManyToManyField(blank=True, related_name='post_authors', to='blogs.blog', verbose_name='Blogs Authored'),
        ),
    ]
