# Generated by Django 4.2.6 on 2023-11-06 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_user_blogs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='blogs',
        ),
    ]
