# Generated by Django 4.2.6 on 2023-11-06 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_remove_blog_author_blogauthor_blog_authors'),
        ('authentication', '0012_remove_user_blogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blogs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_blog_author', to='blogs.blogauthor', verbose_name='Blog Author'),
        ),
    ]
