# Generated by Django 4.2.6 on 2023-12-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_commentreply_reply_commentreplyupvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
