# Generated by Django 4.2.6 on 2023-11-06 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0003_remove_blog_author_blogauthor_blog_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogauthor',
            name='blogs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_authors', to='blogs.blog'),
        ),
        migrations.RemoveField(
            model_name='blog',
            name='authors',
        ),
        migrations.AddField(
            model_name='blog',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='blogs_authored', to=settings.AUTH_USER_MODEL, verbose_name='Authors of the Blog'),
        ),
    ]
