# Generated by Django 4.2.6 on 2023-11-01 10:53

import autoslug.fields
import blog.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=500)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=blog.models.blog_image_file_path)),
                ('is_project', models.BooleanField(default=False, verbose_name='Is Project')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='title', unique=True)),
                ('authors', models.ManyToManyField(blank=True, related_name='posted_blogs', to=settings.AUTH_USER_MODEL, verbose_name='Authors of the Blog')),
            ],
        ),
    ]
