# Generated by Django 4.2.6 on 2023-10-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='host',
            field=models.CharField(default='KUASA', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='BSSC', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=80),
        ),
    ]
